### ISSUE TITLE
Add venue from menu does not store position

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleApp-iOS#196]
Reason: marker is deactivated for that page if navigated to it from the menu. A better approach would be to not let anyone _move_ it once it has been drawn.

**Comment by krzd** [comment]
It is actually because of the 'addVenueCheckIn' check that the marker is not set, which means the problem also exists when adding it from photo location view. So, just need to set it to NO when coming from menu and force the marker on location update. Can fix it now, unless you are already doing it.
