### ISSUE TITLE
Facebook - Get rid of the SDK?

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#237]
Seeing that we just saved us a Twitter expert, we might just do the same with Facebook.
Let's ditch the Facebook SDK and use system accounts for that as well. It makes it also more reliable, probably a bit faster and will solve a couple of issues on iOS 7 we have with it.
It will also slash a significant bit off the ram usage and app size and we don't need to talk about compiling speed.
The real reason why I think we should do it, is because it seems to be possible to do exactly what we want with system accounts: Posting with an image and mentions.
We can only know if it really does work the way we want to, when we try it.
What do you think?

@trigger2896 @uansett @harshirulz

**Comment by uansett** [comment]
If sharing works that is super, but don't you think we will end up in
trouble when we try and fetch friend lists or use profile Ids in searching
for staff members? I doubt that kind of thing is available in the system
accounts

From:  Adam Hani Schakaki notifications@github.com
Reply-To:  shnergle/ShnergleApp-iOS
<reply+i-17585002-743de3ae6f480288e70fabe9b5a14a7e32593738-1151317@reply.git
hub.com>
Date:  Friday, 2 August 2013 23:18
To:  shnergle/ShnergleApp-iOS ShnergleApp-iOS@noreply.github.com
Cc:  Stian Johansen stian.uansett@gmail.com
Subject:  [ShnergleApp-iOS] Facebook - Get rid of the SDK? (#237)

Seeing that we just saved us a Twitter expert, we might just do the same
with Facebook.
Let's ditch the Facebook SDK and use system accounts for that as well. It
makes it also more reliable, probably a bit faster and will solve a couple
of issues on iOS 7 we have with it.
It will also slash a significant bit off the ram usage and app size and we
don't need to talk about compiling speed.
The real reason why I think we should do it, is because it seems to be
possible to do exactly what we want with system accounts: Posting with an
image and mentions.
We can only know if it really does work the way we want to, when we try it.
What do you think?

@trigger2896 https://github.com/trigger2896  @uansett
https://github.com/uansett  @harshirulz https://github.com/harshirulz

‹
Reply to this email directly or view it on GitHub
https://github.com/shnergle/ShnergleApp-iOS/issues/237 .

**Comment by krzd** [comment]
Fetching the friends list is certainly possible and quite easy, haven't looked into fetching profile pictures yet.

**Comment by trigger2896** [comment]
So from my perspective this is a very simple decision.
The priority should always be achieving the desired functionality, with the desired smooth and intuitive UX; it doesn't really matter how we do it.
The next priority it reliability, speed and maintainability - this is where the 'how' may become important.
My understanding is that SDKs only exist to make things easier, but the API itself is the meat of the equation. If we can interact with those APIs better without the SDKs (both FB and Twitter), then for now killing the SDK seems an obvious step.
We can always revert in GitHub, so why not just branch the code to explore with no SDKs? We lose nothing but time in experimenting, and I just consider that necessary R&D! :-)

Is that helpful?

**Comment by krzd** [comment]
I already created a branch with functional login without sdk, posting works actually the same, so doesnt really help with that. We can compare the speed etc on Monday. At least I found some documentation on posting photos, albeit with the custom open graph nonsense.

**Comment by trigger2896** [comment]
Cool, sounds great. I look forward to seeing it Monday!

**Comment by krzd** [comment]
No real speed improvement ...
