### ISSUE TITLE
Search by location (geocoding)

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleApp-iOS#274]

**Comment by krzd** [comment]
Sometimes there an be multiple coordinates as a result, but I tried with hoxton, london and e1 3bq and they all return exactly one coordinate. So using the first hit for that seems appropriate.

@trigger2896 Questions:
- How do we unify that with the search results based on name?
- From that coordinate what radius should we use to search? (Until we have fixed #275 it will be a hardcoded degree radius eg 0.1, but we should be able to make that better, I guess)

That's the code to geocode:

``` smalltalk
[[[CLGeocoder alloc] init] geocodeAddressString:@"Hoxton"
                 completionHandler:^(NSArray* placemarks, NSError* error){
                     for (CLPlacemark* placemark in placemarks) {
                         NSLog(@"hoxton: %f %f", placemark.location.coordinate.latitude, placemark.location.coordinate.longitude);
                     }
                 }];
```

**Comment by trigger2896** [comment]
Yep, use the first coordinate back. I think 2km radius, showing closest to the centre first sounds most sensible.

As for merging the results, it sou ds like we need the server to run a couple of queries for the client app (location and name), merge the results and deliver to the client app as one. I have no clue how to do that though! :-)

Does that help?

Rob

Rob Tregaskes
Co-Founder & CEO
E: robert.tregaskes@shnergle.com
M: (+44) (0)7894 995 532
L: http://uk.linkedin.com/in/robtregaskes
T: @robtregaskes

**Comment by krzd** [comment]
Yeah, regarding merging I meant more like how should it be displayed.
So, we have a search by name and search by location mechanism. Sometimes places are named by locations and vice versa.
So:
- Should be results for search by name be displayed first and then the results by location?
- Should they each in itself by sorted by name?
- Should they maybe be shuffled together somehow?
- Should we try to guess wether a location is meant or a name (based on wether a location is returned from the geocoder)?
- ...

**Comment by trigger2896** [comment]
So on the wireframes search results had icons next to them denoting their category. If we did this anywhere that returned a geocode could be given a 'location pin' icon.

Otherwise I think the best way to do it is to split the results list - a list of matching venues at the top, then a separator, then a list of geocode places.

Its still quite messy, but its the best I can think of at the moment.

Thoughts?

Rob

Rob Tregaskes
Co-Founder & CEO
E: robert.tregaskes@shnergle.com
M: (+44) (0)7894 995 532
L: http://uk.linkedin.com/in/robtregaskes
T: @robtregaskes
