### ISSUE TITLE
Memory pressure when entering venue, then checking in.

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleApp-iOS#336]
May be an issue with apple maps or the image loading on ios7 - maybe an autoreleasepool can help? https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html

**Comment by krzd** [comment]
Autorelease pool should not make a difference plus are not actually meant to br used in this case. Could be because of the way the shareImage is cached, I guess, as the apple maps on around me would be deallocate ld at that point. Or it might help to do the same deallocation and reallocation for the map on the overlay.

**Comment by uansett** [comment]
If the map isn't deallocated properly from the overlay I can see how it can
cause problems. That's possibly it.

**Comment by uansett** [comment]
Was a result of old libraries hanging around - solved by reinstalling the app and cleaning xcode.
