### ISSUE TITLE
REduce size of 'Tap to follow' tappable area - conflicts with back button.

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#349]
Bring the left edge of the tappable area to the right a bit.

**Comment by krzd** [comment]
Cannot confirm a conflict. Could make it a bit smaller the tappable area, but that would lead to some a bit longer names being cut.
This is due to the fact that the two titles are realised as a view, which is tappable, so to make the tappable area smaller, I need to make the view smaller, which leaves less space for the text.
If we should still make it smaller, by about how much? Current width is 200pt.

**Comment by trigger2896** [comment]
Ah ok; I had assumed the area being tapped was associated with 'Tap to follow' text, rather than that actual name of the venue.

Can we change it so that it is associated this way?

**Comment by krzd** [comment]
We could, but it will probably make it much harder to hit it properly to actually follow/unfollow it.

**Comment by trigger2896** [comment]
Could we play about in 1.6 and see what the impact is?

**Comment by krzd** [comment]
Of course.
