### ISSUE TITLE
Sticky Scroller on merchant section of venue page

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleApp-iOS#56]
Once scrolled down to the user intention buttons the scroller seems to get sticky and not allow the map or comments to be visible without constant touch.

For reference the 'Going' Button had been pressed.

**Comment by uansett** [comment]
Solved by scrolling the scrollview back to top before dismissing the venue view. This is the only solution as far as I can see. The issue was that the content stayed in place, while the bounds for the scrollview was reinstantiated in its original position on top. Solution shouldn't cause trouble anyway.
