### ISSUE TITLE
Implement promotions

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleApp-iOS#91]
Last step after all staff management implementations.
requires #89 and #87

**Comment by krzd** [comment]
- ~~Displaying~~
  - ~~Promotion Corner~~
  - ~~Promotion View~~
  - ~~Venue View~~
  - ~~Only display when in time frame and not all redeemed~~
  - ~~Number of redemptions in management and overlay, drop 'out of' if limit is 0~~
  - ~~Promotion 'Detail' View, display real redemptions/expiry~~
- ~~Adding~~
- ~~Editing~~
- ~~Removing~~
- ~~Use tags (ghosting)~~
- ~~Use dictionary~~
- ~~Date Pickers~~
- Redeeming
- ~~History in Profile~~

**Comment by trigger2896** [comment]
At the moment the promotion button for managers appears to go to a 'create promotion' view. There should be an interim view to manage promotions.

That view should show a list of promotions (each one looking like the blue strip that shows on the venue page), which you can tap into for more details and to deactivate. Happy to sketch out what I mean...

**Comment by uansett** [comment]
<img src="https://f.cloud.github.com/assets/1151317/848035/777bb386-f44f-11e2-88b9-278fb8a77ad3.png" width="500px"/>

**Comment by krzd** [comment]
@trigger2896, two question regarding redemptions:

Up to now, we have prepared a whole view for the passcode display. But I think that is confusing, because where should the back button go? It can't go back to the share view, but it also can't (due to technical limitations) go back to the promotion view.
I think it would be better and easier to just show an alert after the check in flow with the passcode. This would also attract the users attention a bit more. After dismissing it would then return to the main screen (as it usually does with the check in flow). Is that alright?

When should be determined wether the user can redeem the promotion, ie it is within the timeframe and the limit is not reached?
We can either do it based on what is displayed, but if there are two more left to claim out of 50, and five users start checking in at the same time, then actually 53 have been claimed.
Or we check it after the check in, and display in the alert the passcode or if it is too late a message saying that he just missed it.
If the latter option is alright, what should the alert display if it is too late?

**Comment by trigger2896** [comment]
So I think your suggestions are good, I would put the redemption flow as:

Tap promotion to get detailed view, tap redeem to enter checkin flow, after share screen show a popup saying pass code or condolence message. The check against time and number redeemed should be after tapping upload on share screen.

Condolence messages should be:
'Bad Luck, you ran out of time to redeem the promotion'
And
'Bad Luck, you just missed the last promotion; someone beat you to it!

The 'redeemed promotions' bit of the profile should then look like the manage promotions list, only they tap the promotion to get a detailed view, pass code, when it was redeemed etc...

Does that all make sense?

**Comment by krzd** [comment]
Yup, for the profile bit it will be as plain as the one for check ins for now. As soon as we fancy up the check ins one, we can make the one for promotions fancy as well.

**Comment by trigger2896** [comment]
Yeah, my only reason for suggesting we make the redemption history look snazzy was so the user could look up the passcode and what the actual promotion was if they dismissed the popup too quickly. Am sure we can do that with the stripped down version right?

**Comment by krzd** [comment]
I want to close this issue at some point, but I will keep it in mind. If the user dismissed it too quickly, he will need to check in again generating more imagery for us ;)
